export const Books = [
    {
        id : 'book1' ,
        author: "Chinua Achebe",
        country: "Nigeria",
        imageLink: "https://c8.alamy.com/comp/FYHFCT/the-front-cover-of-things-fall-apart-by-chinua-achebe-photographed-FYHFCT.jpg",
        language: "English",
        link: "https://en.wikipedia.org/wiki/Things_Fall_Apart\n",
        pages: 209,
        title: "Things Fall Apart",
        year: 1958 ,
        price : 199
    },
    {
        id : 'book2' ,
        author: "Hans Christian Andersen",
        country: "Denmark",
        imageLink: "https://img.freepik.com/free-vector/watercolor-fairytale-concept_52683-34443.jpg?w=2000",
        language: "Danish",
        link: "https://en.wikipedia.org/wiki/Fairy_Tales_Told_for_Children._First_Collection.\n",
        pages: 784,
        title: "Fairy tales",
        year: 1836,
        price : 299
    },
    {
        id : 'book3' ,
        author: "Dante Alighieri",
        country: "Italy",
        imageLink: "https://media.istockphoto.com/id/491065249/photo/dante-and-the-divine-comedy-duomo-cathedral-basilica-florence-it.jpg?s=612x612&w=0&k=20&c=dwGQWUaPOkF3vqis-q2etOfOFretWvbaBtyK6Sd51VE=",
        language: "Italian",
        link: "https://en.wikipedia.org/wiki/Divine_Comedy\n",
        pages: 928,
        title: "The Divine Comedy",
        year: 1315 ,
        price : 259
    },
    {
        id : 'book4' ,
        author: "Unknown",
        country: "Sumer and Akkadian Empire",
        imageLink: "https://c8.alamy.com/comp/MPWMTD/orthostates-depicting-gilgamesh-between-two-minotaur-demigods-holding-up-the-sun-disc-from-tell-hal-MPWMTD.jpg",
        language: "Akkadian",
        link: "https://en.wikipedia.org/wiki/Epic_of_Gilgamesh\n",
        pages: 160,
        title: "The Epic Of Gilgamesh",
        year: -1700 ,
        price : 449
    },
    {
        id : 'book5' ,
        author: "Jane Austen",
        country: "United Kingdom",
        imageLink: "https://upload.wikimedia.org/wikipedia/en/0/03/Prideandprejudiceposter.jpg",
        language: "English",
        link: "https://en.wikipedia.org/wiki/Pride_and_Prejudice\n",
        pages: 226,
        title: "Pride and Prejudice",
        year: 1813 ,
        price : 699
    },
    {
        id : 'book6' ,
        author: "Honor\u00e9 de Balzac",
        country: "France",
        imageLink: "https://m.media-amazon.com/images/I/71IqYfrROTL.jpg",
        language: "French",
        link: "https://en.wikipedia.org/wiki/Le_P%C3%A8re_Goriot\n",
        pages: 443,
        title: "Le P\u00e8re Goriot",
        year: 1835 ,
        price : 359
    },
    {
        id : 'book7' ,
        author: "Samuel Beckett",
        country: "Republic of Ireland",
        imageLink: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/41Tel-2S6DL.jpg",
        language: "French, English",
        link: "https://en.wikipedia.org/wiki/Molloy_(novel)\n",
        pages: 256,
        title: "Molloy, Malone Dies, The Unnamable, the trilogy",
        year: 1952,
        price : 559,
    },
    {
        id : 'book8' ,
        author: "Giovanni Boccaccio",
        country: "Italy",
        imageLink: "https://upload.wikimedia.org/wikipedia/commons/2/2c/Waterhouse_decameron.jpg",
        language: "Italian",
        link: "https://en.wikipedia.org/wiki/The_Decameron\n",
        pages: 1024,
        title: "The Decameron",
        year: 1351 ,
        price : 769
    },
    {
        id : 'book9' ,
        author: "Jorge Luis Borges",
        country: "Argentina",
        imageLink: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1621713120i/426504.jpg",
        language: "Spanish",
        link: "https://en.wikipedia.org/wiki/Ficciones\n",
        pages: 224,
        title: "Ficciones",
        year: 1965,
        price : 999
    },
    {
        id : 'book10' ,
        author: "Emily Bront\u00eb",
        country: "United Kingdom",
        imageLink: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Wuthering_Heights_%281939_poster%29.jpg/684px-Wuthering_Heights_%281939_poster%29.jpg",
        language: "English",
        link: "https://en.wikipedia.org/wiki/Wuthering_Heights\n",
        pages: 342,
        title: "Wuthering Heights",
        year: 1847,
        price : 700
    },
    {
        id : 'book11' ,
        author: "Albert Camus",
        country: "Algeria, French Empire",
        imageLink: "https://upload.wikimedia.org/wikipedia/commons/7/70/L%27%C3%89tranger_%28Albert_Camus%29.jpg",
        language: "French",
        link: "https://en.wikipedia.org/wiki/The_Stranger_(novel)\n",
        pages: 185,
        title: "The Stranger",
        year: 1942,
        price : 99
    }
  
]